/*
 * The compiled-in fallback gauge face.
 *
 * Used when LittleFS cannot be mounted or the stored config is unparseable. It exists so the
 * gauge always has something to display -- a driver turning the ignition on should never be
 * met with a blank screen because a config file went bad.
 *
 * The PX Ranger style boost face, generated by tools/faces/px_faces.py --default: regenerate it
 * there rather than editing it here (docs/gauge-faces.md).
 *
 * Deliberately expressed as XML and parsed on demand, rather than hand-written as a struct:
 * that way the fallback exercises the same parser as every other config, so a parser
 * regression cannot hide behind a path that bypasses it.
 */

#include "gauge_config.h"

#include <stddef.h>

static const char s_default_xml[] =
    "<gauge version=\"1\" id=\"default\">"
    "  <panel shape=\"round\" width=\"466\" height=\"466\"/>"
    "  <source channel=\"boost\" unit=\"psi\" min=\"0\" max=\"30\" damping=\"0.15\"/>"
    "  <face start-angle=\"225\" sweep=\"270\" background=\"#000000\" radius=\"220\">"
    "    <band from=\"0\" to=\"2.42\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"2.58\" to=\"7.42\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"7.58\" to=\"12.42\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"12.58\" to=\"17.42\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"17.58\" to=\"22.42\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"22.58\" to=\"26\" color=\"#ebf0f2\" width=\"12\"/>"
    "    <band from=\"26\" to=\"27.42\" color=\"#ff3030\" width=\"12\"/>"
    "    <band from=\"27.58\" to=\"30\" color=\"#ff3030\" width=\"12\"/>"
    "    <ticks major-every=\"5\" minor-every=\"1\" color=\"#ebf0f2\" band-color=\"true\">"
    "      <major-shape>"
    "        <polygon points=\"-6.5,-7 6.5,-7 0,9\"/>"
    "      </major-shape>"
    "      <minor-shape>"
    "        <polygon points=\"-1.25,-7 1.25,-7 1.25,-1 -1.25,-1\"/>"
    "      </minor-shape>"
    "    </ticks>"
    "    <labels every=\"5\" font=\"montserrat_32\" color=\"#ebf0f2\" radius=\"172\"/>"
    "  </face>"
    "  <needle style=\"taper\" length=\"180\" width=\"12\" color=\"#17caff\" pivot-radius=\"16\"/>"
    "  <readout y=\"300\" font=\"montserrat_48\" format=\"%.1f\" color=\"#ebf0f2\"/>"
    "  <title text=\"BOOST  PSI\" y=\"362\" font=\"montserrat_16\" color=\"#8f9aa0\"/>"
    "  <peak color=\"#ffb000\" length=\"16\" width=\"5\" value-y=\"382\" font=\"montserrat_16\" format=\"%.1f\"/>"
    "  <alert above=\"26\" flash-hz=\"2\" color=\"#ff3030\"/>"
    "</gauge>";

void gauge_config_builtin_default(gauge_config_t *out)
{
    if (out == NULL) {
        return;
    }

    if (gauge_config_parse(s_default_xml, sizeof(s_default_xml) - 1, out) != GAUGE_CONFIG_OK) {
        /*
         * Unreachable unless the built-in XML above is wrong -- which the host tests check
         * for. Fall back to bare defaults so this can never leave garbage behind.
         */
        gauge_config_set_defaults(out);
    }
}
