"""
Generate the PX Ranger styled faces: firmware/assets/gauges/boost.xml and egt.xml, and the
built-in fallback face's XML (printed, for firmware/components/gauge_config/gauge_config_default.c).

Regenerate rather than editing coordinates by hand:

    python tools/faces/px_faces.py            # writes both .xml files
    python tools/faces/px_faces.py --default  # prints the fallback face as a C string

The look is the PX2/PX3 Ranger tachometer (reference photo: obd-display/images/rpm-gauge-px3.jpg),
with the needle outline and palette from the obd-display dashboard (NeedleGaugeView.axaml,
Styles/Colors.axaml). The design notes are in docs/gauge-faces.md.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------- palette (obd-display ipc-*)
OFF_WHITE = "#ebf0f2"  # IpcWhite: ring, pointers, numerals, caption
RED = "#ff3030"        # IpcRedBright: redline ring and pointers, alert
AMBER = "#ffb000"      # IpcAmber: peak marker
NEEDLE = "#17caff"     # NeedleGaugeViewModel's default needle colour
CAP = "#07090b"        # pivot cap
CAP_RIM = "#2b3339"    # the faint rim the cap shows under cluster lighting

# ---------------------------------------------------------------- geometry, from the photo
# Proportions are fractions of the ring's outer radius, measured on rpm-gauge-px3.jpg.
RADIUS = 220                        # scale radius on the 466 px panel (safe area allows 225)
BAND_W = 12                         # ring thickness, ~5.5% of radius
GAP_DEG = 1.4                       # break in the ring at each half-major
CAPTION_Y = 233 - 112               # "RPM x 1000" sits ~0.51 R above centre
TICK_GAP = 6                        # renderer: tick circle = band inner edge - 6 px

# Pointer: an inward triangle hanging off the ring's inner edge (y = -TICK_GAP in the tick frame).
POINTER = f"-7,{-TICK_GAP - 1} 7,{-TICK_GAP - 1} 0,{-TICK_GAP + 12}"


def needle_outline():
    """
    The visible part of obd-display's needle: its body minus the black cover drawn over it (both
    from NeedleGaugeView.axaml, in needle-local units with the tip at +y). The cover's channel is
    narrower than the body up to y=198, so the channel's edge is what shows there; beyond it the
    body's own taper does. The tail is cut just behind the pivot, where the cap hides it.
    """
    right = [(13.5, -20), (15, 98), (23, 123), (19, 198), (21.12, 198), (6, 494), (4, 496)]
    # On the tacho the tip reaches the ring. It stops at 180 px instead: that is the built-in
    # needle's footprint, the size the 60fps budget was measured with, and the editor warns past it.
    tip_px = 180
    k = tip_px / 496.0
    pts = right + [(-x, y) for x, y in reversed(right)]
    # Needle-local +y is the tip; the schema's needle points up (-y).
    return " ".join(f"{x * k:.2f},{-y * k:.2f}".replace(".00", "") for x, y in pts)


def needle_xml(builtin):
    if builtin:
        # The fallback face keeps the built-in needle: it is the last line of defence, so it stays
        # on the longest-tested drawing path (tools/host-tests/test_gauge_config.c asserts this).
        return f'  <needle style="taper" length="180" width="12" color="{NEEDLE}" pivot-radius="16"/>'
    return f"""  <needle color="{NEEDLE}">
    <shape>
      <polygon points="{needle_outline()}"/>
    </shape>
    <hub>
      <circle r="17.5" color="{CAP_RIM}"/>
      <circle r="16" color="{CAP}"/>
    </hub>
  </needle>"""


def bands(vmin, vmax, major, red_from):
    """Ring segments between half-majors, parted by GAP_DEG, split where the redline starts."""
    sweep = 270.0
    gap = GAP_DEG / 2 * (vmax - vmin) / sweep   # half the gap, in value units
    edges = [vmin] + [vmin + major * (i + 0.5) for i in range(int((vmax - vmin) / major))] + [vmax]
    out = []
    for a, b in zip(edges, edges[1:]):
        lo = a if a == vmin else a + gap
        hi = b if b == vmax else b - gap
        if lo < red_from < hi:
            out += [(lo, red_from, OFF_WHITE), (red_from, hi, RED)]
        else:
            out.append((lo, hi, RED if lo >= red_from else OFF_WHITE))
    assert len(out) <= 8, "the schema allows 8 bands"
    return out


def num(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def face(gid, comment, channel, unit, vmax, major, red_from, caption, damping, fmt, label_font, label_r,
         builtin_needle=False):
    band_xml = "\n".join(
        f'    <band from="{num(a)}" to="{num(b)}" color="{c}" width="{BAND_W}"/>'
        for a, b, c in bands(0, vmax, major, red_from))
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  {comment}
  PX Ranger style: see docs/gauge-faces.md. Generated by tools/faces/px_faces.py; edit that, not this.
  Schema: docs/gauge-config-schema.md
-->
<gauge version="1" id="{gid}">
  <panel shape="round" width="466" height="466"/>
  <source channel="{channel}" unit="{unit}" min="0" max="{vmax}" damping="{damping}"/>

  <face start-angle="225" sweep="270" background="#000000" radius="{RADIUS}">
{band_xml}
    <ticks major-every="{major}" minor-every="0" color="{OFF_WHITE}" band-color="true">
      <major-shape>
        <polygon points="{POINTER}"/>
      </major-shape>
    </ticks>
    <labels every="{major}" font="{label_font}" color="{OFF_WHITE}" radius="{label_r}"/>
  </face>

{needle_xml(builtin_needle)}

  <title text="{caption}" y="{CAPTION_Y}" font="montserrat_20" color="{OFF_WHITE}"/>
  <readout y="300" font="montserrat_48" format="{fmt}" color="{OFF_WHITE}"/>

  <peak color="{AMBER}" length="{BAND_W + 4}" width="5" font="montserrat_16" format="{fmt}"/>
  <alert above="{num(red_from)}" flash-hz="2" color="{RED}"/>
</gauge>
"""


BOOST = dict(gid="boost", comment="Boost gauge, 0-30 PSI, redline from 26 as on the obd-display boost dial.",
             channel="boost", unit="psi", vmax=30, major=5, red_from=26, caption="BOOST  PSI",
             damping="0.15", fmt="%.1f",
             # Numerals at ~0.8 R, as on the tacho, pulled in far enough to clear the pointers at 3
             # and 9 o'clock, where a number is set sideways to the radius.
             label_font="montserrat_32", label_r=172)
EGT = dict(gid="egt", comment="Exhaust gas temperature gauge, 0-900 C, redline from 750.",
           channel="egt", unit="C", vmax=900, major=150, red_from=750, caption="EGT  °C",
           damping="0.25", fmt="%.0f",
           # Three-digit numbers: the tacho only ever has one, so a size down to keep the same clearance.
           label_font="montserrat_26", label_r=166)


def c_string(xml):
    """The face as C string literal lines, without the XML declaration and comment."""
    body = xml[xml.index("<gauge"):].strip().splitlines()
    return "\n".join('    "' + line.replace('\\', '\\\\').replace('"', '\\"') + '"'
                     for line in body if line.strip())


if __name__ == "__main__":
    if "--default" in sys.argv:
        print(c_string(face(**{**BOOST, "gid": "default", "builtin_needle": True})))
        sys.exit(0)
    out = ROOT / "firmware" / "assets" / "gauges"
    for spec in (BOOST, EGT):
        (out / f"{spec['gid']}.xml").write_text(face(**spec), encoding="utf-8", newline="\n")
        print("wrote", out / f"{spec['gid']}.xml")
