/* GENERATED by tools/splash/make_splash.py. Edit that, not this. */
#pragma once

/* All in scene pixels, from the scene's top-left corner. */
#define SPLASH_SCENE_SIZE 466
#define SPLASH_BAR_X      116
#define SPLASH_BAR_Y      324
#define SPLASH_BAR_W      234
#define SPLASH_BAR_H      13
#define SPLASH_SPARK_SIZE 24
