# Generates the C table of face editor files that net_svc serves at /editor/ (ADR 0008).
# Run by the custom command in this component's CMakeLists.txt:
#
#   cmake -D EDITOR_DIR=<tools/config-app> -D FACES_DIR=<assets/gauges> -D OUT=<file.c> -P editor_bundle.cmake
#
# Every file is gzipped here and sent as-is with Content-Encoding: gzip, so nothing is decompressed
# on the device. Paths are relative to /editor/; the shipped faces go under examples/, where the
# editor looks for them, matching the layout of the GitHub Pages site.
cmake_minimum_required(VERSION 3.19)

if(NOT EXISTS "${EDITOR_DIR}/index.html")
    message(FATAL_ERROR "face editor not found at ${EDITOR_DIR}")
endif()

set(work "${OUT}.d")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")

set(arrays "")
set(entries "")
set(count 0)
set(total 0)

macro(add_file src rel)
    set(gz "${work}/${count}.gz")
    file(ARCHIVE_CREATE OUTPUT "${gz}" PATHS "${src}" FORMAT raw COMPRESSION GZip COMPRESSION_LEVEL 9)
    file(READ "${gz}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR total "${total} + ${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND arrays "static const uint8_t file_${count}[] = {${bytes}};\n")
    string(APPEND entries "    {\"${rel}\", file_${count}, sizeof(file_${count})},\n")
    math(EXPR count "${count} + 1")
endmacro()

file(GLOB css RELATIVE "${EDITOR_DIR}" "${EDITOR_DIR}/css/*.css")
file(GLOB js RELATIVE "${EDITOR_DIR}" "${EDITOR_DIR}/js/*.js")
file(GLOB faces RELATIVE "${FACES_DIR}" "${FACES_DIR}/*.xml")
list(SORT css)
list(SORT js)
list(SORT faces)

foreach(rel index.html ${css} ${js})
    add_file("${EDITOR_DIR}/${rel}" "${rel}")
endforeach()
foreach(rel ${faces})
    add_file("${FACES_DIR}/${rel}" "examples/${rel}")
endforeach()

file(WRITE "${OUT}"
    "/* Generated by editor_bundle.cmake from tools/config-app. Do not edit. */\n\n"
    "#include \"net_svc_editor_files.h\"\n\n"
    "${arrays}\n"
    "const net_svc_editor_file_t net_svc_editor_files[] = {\n${entries}};\n\n"
    "const size_t net_svc_editor_file_count = sizeof(net_svc_editor_files) / sizeof(net_svc_editor_files[0]);\n")

file(REMOVE_RECURSE "${work}")
message(STATUS "face editor: ${count} files, ${total} bytes gzipped")
