idf_component_register(
    SRCS
        "app_main.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        app_settings
        app_ui
        board_profile
        gauge_config
        gauge_perf
        gauge_render
        gauge_store
        net_svc
        nvs_flash
        esp_timer
        app_update
)
